version: "3"
services:
  db-interactions:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: creative-hub-interactions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  microservice-interactions:
    build: .
    image: creative-hub/microservice-interactions:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-interactions:5432/creative-hub-interactions
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - db-interactions